# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
name = "Contact"
pageRef = "contact"
weight = 10

[[main]]
name = "Newsletter"
parent = "Contact"
pageRef = "newsletter"
weight = 12

[[main]]
name = "Submissions"
parent = "Contact"
pageRef = "submissions"
weight = 14

[[main]]
name = "Publications"
pageRef = "publications"
weight = 20

[[main]]
name = "Stories"
parent = "Publications"
pageRef = "stories"
weight = 22

[[main]]
name = "Authors"
parent = "Publications"
pageRef = "authors"
weight = 24

[[main]]
name = "Series"
parent = "Publications"
pageRef = "series"
weight = 26

[[main]]
name = "About Us"
pageRef =  "about-us"
weight = 30

[[main]]
name = "Our goals"
parent = "About Us"
pageRef = "our-goals"
weight = 32

[[main]]
name = "Logophilia Essentials"
parent = "About Us"
pageRef = "logophilia-essentials"
weight = 34

[[main]]
name = "Calling All Authors"
parent = "About Us"
pageRef = "calling-all-authors"
weight = 36

[[main]]
name = "Standard Terms for Publication"
parent = "About Us"
pageRef = "standard-terms-for-publication"
weight = 38

[[main]]
name = "The Logophilia Edge"
parent = "About Us"
pageRef = "the-logophilia-edge"
weight = 40

[[main]]
name = "Understanding ISBNs: Variations and Importance"
parent = "About Us"
pageRef = "understanding-isbns-variations-and-importance"
weight = 42

[[main]]
name = "Our Customers by Orders"
parent = "About Us"
pageRef = "our-customers-by-orders"
weight = 44

[[main]]
name = "The Director, Without a Service Weapon"
parent = "About Us"
pageRef = "the-director-without-a-service-weapon"
weight = 46

[[main]]
name = "Idoru Toei"
parent = "About Us"
pageRef = "idoru-toei"
weight = 48

[[main]]
name = "Terms of Use"
pageRef = "terms-of-use"
weight = 50

[[main]]
name = "Affiliate Disclosure"
parent = "Terms of Use"
pageRef = "affiliate-disclosure"
weight = 52

[[main]]
name = "Privacy Policy"
parent = "Terms of Use"
pageRef = "privacy-policy"
weight = 54

[[main]]
name = "Cookie Policy"
parent = "Terms of Use"
pageRef = "cookie-policy-eu"
weight = 56

[[main]]
name = "Shop Terms and Conditions"
parent = "Terms of Use"
pageRef = "shop-terms-and-conditions"
weight = 58

[[main]]
name = "Right of Withdrawal"
parent = "Terms of Use"
pageRef = "right-of-withdrawal"
weight = 60

[[main]]
name = "Review Authenticity"
parent = "Terms of Use"
pageRef = "review-authenticity"
weight = 62

[[main]]
name = "Shipping Terms"
parent = "Terms of Use"
pageRef = "shipping-terms"
weight = 64

[[subnavigation]]
name = "Lea EPUB Anvil"
pre = "github"
url = "https://github.com/SimStim/Lea.git"
weight = 70

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
